# Generated by Django 6.0 on 2025-12-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('can_i_use_url', models.URLField(blank=True)),
                ('code_preview', models.TextField()),
                ('preview_language', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnippetBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(blank=True, choices=[('p', 'Paragraph'), ('code', 'Code'), ('h3', 'Heading')], max_length=10, null=True)),
                ('language', models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], max_length=20, null=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='snippets.snippet')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='CssSnippet',
        ),
    ]
